language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

install:
  - npm install

env:
  global:
    - NODE_ENV=test

branches:
  only:
    - develop
    - master

services:
  - postgresql

before_script:
  - psql -c 'create database stockMgt;' -U postgres

script:
  - npm test

after_success:
- npm run coverage
- npm run coveralls