language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

env:
  global:
    - NODE_ENV=test

branches:
  only:
    - develop
    - master

services:
  - postgresql

addons:
  postgresql: "10"
 
install:
- npm install -q --no-color --no-progress

before_script:
  - psql -c 'create database stock_mgt;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_success:
  - npm run coverage
  - npm run coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
