language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

env:
  global:
    - NODE_ENV=test

branches:
  only:
    - develop
    - master

services:
  - postgresql

addons:
  postgresql: "10"

before_script:
  - psql -c 'create database stock_mgt;' -U postgres

script:
  - npm test

after_success:
- npm run coverage
- npm run coveralls