version: '3'

services:
  node:
    image: chuksjoe/stock-mgt-backend
    build: .
    volumes:
      - .:/usr/src/app
      - ./node_modules
    networks:
      - backend
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:latest
    networks:
      - backend
    ports:
      - '5432:5432'

networks:
  backend:
    driver: bridge
